// Every on-screen Mongolian string lives here, grouped by screen.
export const strings = {
  index: {
    title: "Сонсъё",
    modes: {
      home: "Гэр",
      queue: "Дугаар",
      name: "Нэр",
      talk: "Ярих",
    },
    shortcuts: {
      history: "Түүх",
      settings: "Тохиргоо",
      interpreter: "Хэлмэрч",
    },
  },
  queue: {
    testAlert: "Мэдэгдэл турших",
    title: "Дугаар",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    ticketLabel: "Таны дугаар",
    placeholder: "А024",
    example: "Жишээ: А024 · 24",
    invalidTicket: "Дугаараа зөв оруулна уу. Жишээ: А024 эсвэл 24",
    keepOpen: "Аппаа хаахгүй",
    waiting: "Зарлал хүлээж байна",
    recent: "Сүүлд",
    emptyRecent: "Одоогоор зарлал алга",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  name: {
    testAlert: "Мэдэгдэл турших",
    title: "Нэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    nameLabel: "Таны нэр",
    placeholder: "Болд",
    hint: "Дуудуулах нэрээ оруулна уу",
    invalidName: "Нэрээ оруулна уу",
    waiting: "Таны нэрийг дуудахыг хүлээж байна",
    keepOpen: "Аппаа хаахгүй",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  home: {
    testKnock: "Тогших мэдэгдэл турших",
    testDoorbell: "Хонхны мэдэгдэл турших",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
    title: "Гэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    sounds: {
      knock: "Хаалга",
      bell: "Хонх",
      alarm: "Сэрүүлэг",
    },
  },
} as const;
