// Every on-screen Mongolian string lives here, grouped by screen.
export const strings = {
  index: {
    title: "Сонсъё",
    modes: {
      home: "Гэр",
      queue: "Дугаар",
      name: "Нэр",
      talk: "Ярих",
    },
    shortcuts: {
      history: "Түүх",
      settings: "Тохиргоо",
      interpreter: "Хэлмэрч",
    },
  },
  queue: {
    testAlert: "Мэдэгдэл турших",
    title: "Дугаар",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    ticketLabel: "Таны дугаар",
    placeholder: "А024",
    example: "Жишээ: А024 · 24",
    invalidTicket: "Дугаараа зөв оруулна уу. Жишээ: А024 эсвэл 24",
    keepOpen: "Аппаа хаахгүй",
    waiting: "Зарлал хүлээж байна",
    recent: "Сүүлд",
    emptyRecent: "Одоогоор зарлал алга",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  name: {
    testAlert: "Мэдэгдэл турших",
    title: "Нэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    nameLabel: "Таны нэр",
    placeholder: "Болд",
    hint: "Дуудуулах нэрээ оруулна уу",
    invalidName: "Нэрээ оруулна уу",
    waiting: "Таны нэрийг дуудахыг хүлээж байна",
    keepOpen: "Аппаа хаахгүй",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  home: {
    testKnock: "Тогших мэдэгдэл турших",
    testDoorbell: "Хонхны мэдэгдэл турших",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
    title: "Гэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    sounds: {
      knock: "Хаалга",
      bell: "Хонх",
      alarm: "Сэрүүлэг",
    },
  },
  talk: {
    incoming: {
      title: "Нөгөө хүний яриа",
      instruction: "Сонсох дарж, нэг өгүүлбэр хэлүүлээд «Дуусгах» дарна. 8 секундэд автоматаар дуусна.",
      privacy: "Зөвшөөрсөн хүний яриаг л бичүүлнэ үү. Богино бичлэг яриа танихын тулд ElevenLabs руу илгээгдэнэ.",
      listen: "Сонсох", finish: "Дуусгах", cancel: "Цуцлах",
      preparing: "Микрофон бэлдэж байна…", recording: "Сонсож байна…", processing: "Яриаг таньж байна…",
      transcript: "Танигдсан яриа", showSign: "Дохио үзэх", noMatch: "Энэ өгүүлбэрийн дохио одоогоор байхгүй.",
      empty: "Яриа танигдсангүй. Дахин оролдоно уу.",
      helpNotice: "Энэ нь «туслах» гэсэн гол үгийн дохио. «Танд юугаар туслах вэ?» асуултын бүтэн орчуулга биш.",
      phrases: { greeting: "Сайн байна уу?", thanks: "Баярлалаа", sorry: "Уучлаарай", goodbye: "Баяртай", helpQuestion: "Туслах — гол үгийн дохио" },
      errors: {
        permission: "Микрофон ашиглах зөвшөөрөл өгнө үү.",
        recording: "Микрофоноор бичлэг эхлүүлж чадсангүй. Expo Go-ийн микрофоны зөвшөөрлийг шалгана уу.",
        access: "Серверийн API key дээр Speech to Text → Access эрхийг нээнэ үү.",
        configuration: "Яриа таних серверийн тохиргоо дутуу байна.",
        provider: "Яриа таньж чадсангүй. Speech to Text эрх, үлдэгдэл болон серверийг шалгана уу.",
        network: "Сервертэй холбогдож чадсангүй. Дахин оролдоно уу.",
      },
      recordingDetails: "Микрофоны алдааны мэдээлэл",
      replay: "Бичлэгээ сонсож шалгах", replayStop: "Бичлэгийг зогсоох",
      replayLoading: "Бичлэгийг нээж байна…",
      replayHint: "Энэ шалгалтыг сонсдог хүнтэй хамт хийнэ үү. Сая бичсэн аудиог утсан дээрээс тоглуулна. Дуу тод сонсогдож байгаа эсэхийг шалгаарай.",
      replayError: "Бичлэгийг тоглуулж чадсангүй. Дахин бичээд шалгана уу.",
    },
    title: "Харилцах",
    back: "Буцах",
    instruction: "Дохио сонгоод хэлүүлээрэй",
    category: "Өдөр тутам",
    phrases: { greeting: "Сайн байна уу?", thanks: "Баярлалаа" },
    watchSign: "Дохио үзэх",
    speak: "Хэлүүлэх",
    selected: "Сонгосон өгүүлбэр",
    repeat: "Дахин хэлэх",
    stop: "Зогсоох",
    close: "Хаах",
    loading: "Аудио бэлдэж байна…",
    videoLoading: "Дохионы бичлэг ачаалж байна…",
    playing: "Хэлж байна",
    source: "Дохионы эх сурвалж: mnsl.mn",
    signUnavailable: "Дохионы бичлэгийг нээж чадсангүй",
    errors: {
      configuration: "Аудионы тохиргоо дутуу байна. Бичвэрээ харуулж болно.",
      provider: "Аудио үүсгэж чадсангүй. Дахин оролдоно уу.",
      network: "Холболт тасарлаа. Дахин оролдоно уу.",
    },
  },
  history: {
    title: "Түүх",
    back: "Буцах",
    empty: "Түүх хоосон байна",
    filters: {
      all: "Бүгд",
      home: "Гэр",
      queue: "Дараалал",
      name: "Нэр",
    },
    // Placeholder rows until services/storage exists.
    sample: {
      queue: { title: "А-024 дугаар · 3-р цонх", time: "Өнөөдөр 14:35" },
      knock: { title: "Хаалга тогшив", time: "Өнөөдөр 12:10" },
      doorbell: { title: "Хаалганы хонх", time: "Өнөөдөр 09:02" },
      name: { title: "Нэр дуудсан", time: "Өчигдөр 18:20" },
    },
  },
  settings: {
    title: "Тохиргоо",
    back: "Буцах",
    alerts: "Мэдэгдэл",
    vibration: "Чичиргээ",
    color: "Өнгө",
    light: "Гэрэл",
    appearance: "Харагдац",
    textSize: "Бичиг",
    textSizes: {
      large: "Том",
      xlarge: "Маш том",
    },
  },
} as const;
