// Every on-screen Mongolian string lives here, grouped by screen.
export const strings = {
  index: {
    title: "Сонсъё",
    modes: {
      home: "Гэр",
      queue: "Дугаар",
      name: "Нэр",
      talk: "Ярих",
    },
    shortcuts: {
      history: "Түүх",
      settings: "Тохиргоо",
      interpreter: "Хэлмэрч",
    },
  },
  queue: {
    testAlert: "Мэдэгдэл турших",
    title: "Дугаар",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    ticketLabel: "Таны дугаар",
    placeholder: "А024",
    example: "Жишээ: А024 · 24",
    invalidTicket: "Дугаараа зөв оруулна уу. Жишээ: А024 эсвэл 24",
    keepOpen: "Аппаа хаахгүй",
    waiting: "Зарлал хүлээж байна",
    recent: "Сүүлд",
    emptyRecent: "Одоогоор зарлал алга",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  name: {
    testAlert: "Мэдэгдэл турших",
    title: "Нэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    nameLabel: "Таны нэр",
    placeholder: "Болд",
    hint: "Дуудуулах нэрээ оруулна уу",
    invalidName: "Нэрээ оруулна уу",
    waiting: "Таны нэрийг дуудахыг хүлээж байна",
    keepOpen: "Аппаа хаахгүй",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
  },
  home: {
    testKnock: "Тогших мэдэгдэл турших",
    testDoorbell: "Хонхны мэдэгдэл турших",
    preview: "Туршилтын төлөв — аудио таних холболт хийгдээгүй",
    title: "Гэр",
    back: "Буцах",
    listen: "Сонсох",
    listening: "Сонсож байна",
    tapToStop: "Дахин дарж зогсооно",
    sounds: {
      knock: "Хаалга",
      bell: "Хонх",
      alarm: "Сэрүүлэг",
    },
  },
  talk: {
    title: "Харилцах",
    back: "Буцах",
    // Keep the previous talk screen working until the screen PR is merged.
    staff: "Ажилтан",
    sampleTranscript: "Та захиалгын дугаараа хэлнэ үү.",
    inputLabel: "Хариу бичих",
    inputPlaceholder: "Миний дугаар 125",
    quickReplies: [
      "Дахин хэлнэ үү",
      "Бичгээр харуулна уу",
      "Удаан ярина уу",
      "Баярлалаа",
    ],
    show: "Харуулах",
    instruction: "Дохио сонгоод хэлүүлээрэй",
    category: "Өдөр тутам",
    phrases: { greeting: "Сайн байна уу?", thanks: "Баярлалаа" },
    watchSign: "Дохио үзэх",
    speak: "Хэлүүлэх",
    selected: "Сонгосон өгүүлбэр",
    repeat: "Дахин хэлэх",
    stop: "Зогсоох",
    close: "Хаах",
    loading: "Аудио бэлдэж байна…",
    videoLoading: "Дохионы бичлэг ачаалж байна…",
    playing: "Хэлж байна",
    source: "Дохионы эх сурвалж: mnsl.mn",
    signUnavailable: "Дохионы бичлэгийг нээж чадсангүй",
    errors: {
      configuration: "Аудионы тохиргоо дутуу байна. Бичвэрээ харуулж болно.",
      provider: "Аудио үүсгэж чадсангүй. Дахин оролдоно уу.",
      network: "Холболт тасарлаа. Дахин оролдоно уу.",
    },
  },
  history: {
    title: "Түүх",
    back: "Буцах",
    empty: "Түүх хоосон байна",
    filters: {
      all: "Бүгд",
      home: "Гэр",
      queue: "Дараалал",
      name: "Нэр",
    },
    // Placeholder rows until services/storage exists.
    sample: {
      queue: { title: "А-024 дугаар · 3-р цонх", time: "Өнөөдөр 14:35" },
      knock: { title: "Хаалга тогшив", time: "Өнөөдөр 12:10" },
      doorbell: { title: "Хаалганы хонх", time: "Өнөөдөр 09:02" },
      name: { title: "Нэр дуудсан", time: "Өчигдөр 18:20" },
    },
  },
  settings: {
    title: "Тохиргоо",
    back: "Буцах",
    alerts: "Мэдэгдэл",
    vibration: "Чичиргээ",
    color: "Өнгө",
    light: "Гэрэл",
    appearance: "Харагдац",
    textSize: "Бичиг",
    textSizes: {
      large: "Том",
      xlarge: "Маш том",
    },
  },
} as const;
