import { expect, test } from "@jest/globals";

import { matchIncomingSign, type IncomingSignId } from "./incomingSigns";

const CASES: [string, IncomingSignId | null][] = [
  ["Сайн байна уу?", "greeting"],
  ["  САЙН   БАЙНА УУ!  ", "greeting"],
  ["Сайн уу", "greeting"],
  ["Та сайн байна уу?", "greeting"],
  ["Сайн байн уу", "greeting"],
  ["Сайн байну", "greeting"],
  ["Сайн уу та?", "greeting"],
  ["Баярлалаа.", "thanks"],
  ["Маш их баярлалаа", "thanks"],
  ["Их баярлалаа", "thanks"],
  ["Танд баярлалаа", "thanks"],
  ["Таньд баярлалаа", "thanks"],
  ["Талархаж байна", "thanks"],
  ["Уучлаарай!", "sorry"],
  ["Өршөөгөөрэй", "sorry"],
  ["Намайг уучлаарай", "sorry"],
  ["Уучлаарай та", "sorry"],
  ["Хүлцэл өчье", "sorry"],
  ["Баяртай", "goodbye"],
  ["Түр баяртай", "goodbye"],
  ["За баяртай", "goodbye"],
  ["Танд юугаар туслах вэ?", "helpQuestion"],
  ["Юугаар туслах вэ?", "helpQuestion"],
  ["Танд юугаар туслах бэ?", "helpQuestion"],
  ["Танд юугаар туслах уу?", "helpQuestion"],
  ["Юугаар туслах уу?", "helpQuestion"],
  ["Танд юугаар туслаху", "helpQuestion"],
  ["Юугаар туслаху", "helpQuestion"],
  ["Таньд юугаар туслах вэ?", "helpQuestion"],
  ["Таньд юугаар туслах уу?", "helpQuestion"],
  ["Таньд юугаар туслаху", "helpQuestion"],
  ["Танд яаж туслах вэ?", "helpQuestion"],
  ["Таньд яаж туслах вэ?", "helpQuestion"],
  ["Яаж туслах вэ?", "helpQuestion"],
  ["Би танд юугаар туслах вэ?", "helpQuestion"],
  ["Би таньд юугаар туслах вэ?", "helpQuestion"],
  ["Танд ямар тусламж хэрэгтэй вэ?", "helpQuestion"],
  ["Тусламж хэрэггүй", null],
  ["Танд туслахгүй", null],
  ["Танд юугаар туслах вэ гэж асуугаагүй", null],
  ["Танд ямар тусламж хэрэгтэйг мэдэхгүй", null],
  ["Надад туслаач", null],
  ["Танд баярлалаа гэж хэлээгүй", null],
  ["Намайг уучлаарай гэж хэлээгүй", null],
  ["Түр баяртай биш", null],
  ["Senberno", null],
  ["Баяртай биш байна", null],
  ["Сайн байна уу гэж хэлээгүй", null],
  ["Туслах", null],
  ["", null],
];

test.each(CASES)("maps %s to %s without guessing unsupported sentences", (transcript, expected) => {
  expect(matchIncomingSign(transcript)).toBe(expected);
});
